# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: MAC Scanner
version: "0.0.2"
slug: macscanner
description: Allows for scanning and tracking of MAC addresses on the local network. Results fed into both entity and MQTT
url: "https://github.com/MKMakerSpace/Home-Addistant-addons-MKMake"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
startup: before
host_network: true
map:
  - config:rw
  - share:rw
  - ssl

options:
  refresh_rate: 60
  mqtt_server_address: "192.168.1.7"
  mqtt_server_port: 1883
  read_mqtt_from_secrets: 1
  mqtt_server_username: ""
  mqtt_server_password: ""
  mqtt_server_topic: "macscanner"
  nmap_target: "192.168.1.0/24"
  nmap_speed: 5

schema:
  refresh_rate: int(3,)
  mqtt_server_address: str
  mqtt_server_port: port
  read_mqtt_from_secrets: "bool?"
  mqtt_server_username: "str?"
  mqtt_server_password: "password?"
  mqtt_server_topic: str
  nmap_target: str
  nmap_speed: int(1,5)

image: "ghcr.io/mkmakerSpace/{arch}-home-addistant-addons-mkmake"
